# Use postgres/example user/password credentials
version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5400:5432
    environment:
      POSTGRES_PASSWORD: example
